# Generated by Django 3.2 on 2021-06-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book name')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Short description')),
                ('description', models.TextField(verbose_name='About book')),
                ('price', models.CharField(max_length=100, verbose_name='Book price')),
                ('genre', models.CharField(max_length=20, verbose_name='Genre')),
                ('author', models.CharField(max_length=20, verbose_name='Author')),
                ('year', models.CharField(max_length=100, verbose_name='Date of issue')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
